spring.application.name=backend-anse

# CONFIGURACION DE BD - MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/anse_db?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACION JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# CONFIGURACION JWT
jwt.secret=MurcielagoEsternocleidomastoideoAseguramientoProyectoANSE2026
jwt.expiration=86400000

# SECURITY
spring.security.headers.frame-options=disable